{{- if .Values.secretsManager }}
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: "{{ .Release.Name }}-spc"
spec:
  provider: aws
  secretObjects:
    - secretName: "{{ .Release.Name }}-secrets"
      type: Opaque
      data:
        {{- range $key, $value := .Values.secretsManager.objects }}
        - objectName: {{ $key }}
          key: {{ $value | quote }}
        {{- end }}
  parameters:
    objects: |
      - objectName: {{ .Values.secretsManager.name }} 
        objectType: secretsmanager
        jmesPath:
            {{- range $key, $value := .Values.secretsManager.objects }}
            - path: {{ $key }}
              objectAlias: {{ $value | quote }}
            {{- end }}
{{- end }}