name: Project tester deploy
on:
  workflow_dispatch:
  push:
    paths:
      - "src/**"
      - "Dockerfile"
      - "pom.xml"
    branches:
      - "main"

jobs:
  build:
    needs: pact
    uses: endroca/project-tester/.github/workflows/build.yaml@main
    with:
      github-event-sha: "${{ github.event.pull_request.head.sha }}"
      project-name: "project-tester"
      file-jar: "project-tester-1.0-SNAPSHOT.jar"
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-region: us-east-1
      github-token: ${{ secrets.CI_GITHUB_TOKEN }}

  development:
    needs: build
    uses: endroca/project-tester/.github/workflows/deploy.yaml@main
    with:
      environment: "development"
      github-event-sha: "${{ github.event.pull_request.head.sha }}"
      project-name: "project-tester"
      image-tag: "${{ github.run_number }}"
    secrets:
      aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
      aws-region: us-east-1
      github-token: ${{ secrets.CI_GITHUB_TOKEN }}
      argocd-user: ${{ secrets.ARGOCD_USER }}
      argocd-password: ${{ secrets.ARGOCD_PASSWORD }}
